#!/bin/bash -e
set -e

#DEBHELPER#

if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
  dpkg-maintscript-helper rm_conffile /etc/kde3/kdeglobals 6.0.1 -- "$@"
fi

if [ "$1" = configure ] && dpkg --compare-versions "$2" lt-nl 7; then
  update-alternatives --remove desktop-grub /usr/share/images/desktop-base/moreblue-orbit-grub.png
fi

if [ "$1" = "configure" -o "$1" = "abort-upgrade" ]; then
    # Alternatives for the background
    while read background priority; do
        update-alternatives --install \
            /usr/share/images/desktop-base/desktop-background \
            desktop-background \
            /usr/share/images/desktop-base/$background $priority
    done << EOF
anger-wallpaper_1280x1024.svg 60
anger-wallpaper_1600x1200.svg 60
anger-wallpaper_1920x1080.svg 60
anger-wallpaper_1920x1200.svg 60
anger-wallpaper_2560x1080.svg 60
blue-wallpaper_1280x1024.svg 65
blue-wallpaper_1600x1200.svg 65
blue-wallpaper_1920x1080.svg 70
blue-wallpaper_1920x1200.svg 65
blue-wallpaper_2560x1080.svg 65
gray-wallpaper_1600x1200.svg 55
gray-wallpaper_1280x1024.svg 55
gray-wallpaper_1920x1080.svg 55
gray-wallpaper_1920x1200.svg 55
EOF

    # Set up an alternative for the XML version of the background
    # (for GNOME)
    while read desktopbackground priority; do
        update-alternatives --install \
            /usr/share/images/desktop-base/desktop-background.xml \
            desktop-background.xml \
            /usr/share/images/desktop-base/$desktopbackground $priority
    done << EOF
anger.xml 10
blue.xml 20
gray.xml 15
EOF

    # Alternatives for the splash
    while read splash priority; do
        update-alternatives --install \
            /usr/share/images/desktop-base/desktop-splash \
            desktop-splash \
            /usr/share/images/desktop-base/$splash $priority
    done << EOF
pardus-splash.png 50
EOF

    # Alternatives for grub
    ## Favor widescreen / hi-res background for efi installations
    num_grub_efi_installed=$(dpkg-query --list "grub-efi*" | grep "^i" | wc -l)
    if [ $num_grub_efi_installed -gt 0 ] ; then
        pardus_grub_prio=15
        pardus_grub_1920_prio=20
    else
        pardus_grub_prio=20
        pardus_grub_1920_prio=15
    fi
    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-grub.png \
        desktop-grub \
        /usr/share/images/desktop-base/pardus-grub.png $pardus_grub_prio
    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-grub.png \
        desktop-grub \
        /usr/share/images/desktop-base/pardus-grub-1920x1080.png $pardus_grub_1920_prio

    while read background priority; do
        update-alternatives --install \
            /usr/share/images/desktop-base/desktop-grub.png \
            desktop-grub \
            /usr/share/images/desktop-base/$background $priority
    done << EOF
EOF

    # GRUB background
    if which update-grub2 > /dev/null ; then
        sync
        update-grub2 || true
    fi

    if [ -x /usr/sbin/update-initramfs ]; then
        update-initramfs -u
    fi

fi
